iter 13: error handling
aykuli/observer pull request #13
Opened 2024-04-06 13:39 UTC by aykuli

2024-04-06 17:34 UTC, aykuli commented on cmd/server/handlers/handlers.go
> +				value := m.MemStorage.GaugeMetrics[metricName]
зачем мне тут лишняя перменна? нельзя сразу respMetric.Value = &m.MemStorage.GaugeMetrics[metricName]
похоже нельзя из-за мап

2024-04-06 17:36 UTC, aykuli commented on cmd/server/handlers/handlers.go
> +			switch metricType {
respMetric, err = m.localTake(metricType, metricName)

2024-04-06 17:37 UTC, aykuli commented on cmd/server/handlers/handlers.go
> +				value, ok := m.MemStorage.CounterMetrics[metricName]
```suggestion
				delta, ok := m.MemStorage.CounterMetrics[metricName]
```

2024-04-16 06:00 UTC, valentinsoe submitted a review, later dismissed
Спасибо за работу, написал комментарии.
Из критически важного:
1) код хендлеров не должен зависеть от типа используемого хранилища.
2) если для выполнения одного запроса(HTTP) используется несколько запросов к БД - нужно использовать транзакции
3) хранить дельту в БД не в тексте, а числом
Из того, что лучше исправить чтобы не стрелять самому себе в ногу лишними сложностями - убрать отдельную табличку для имен. 3 нормальная форма здесь приносит больше проблем чем преимуществ

2024-04-16 06:00 UTC, valentinsoe commented on cmd/server/main.go
> +	workWithFile := config.Options.DatabaseDsn == "" && config.Options.FileStoragePath != ""
Рекомендую настройку хранилища отнести в отдельную функцию

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/db/postgres/postgres.go
> +	metricNamesRepo := repository.NewMetricNamesRepository(conn)
А зачем нам отдельно хранить имена метрик?

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/decompressor/decompressor.go
> +package decompressor
Кажется это лишний пакет

2024-04-16 06:00 UTC, valentinsoe commented on internal/compressor/compressor.go
> +		supportsGzip := strings.Contains(acceptEncoding, "gzip")
Это не единственное условие, требуемое для принятия решения о сжатии по заданию. Также мы должны опираться на возвращаемый Content-Type

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/repository/metric_names_repository.go
> +	createMetricQuery     = `INSERT INTO metric_names (name) VALUES ($1) RETURNING id, name`
CreateMetricNameQuery?
SelectAllMetricNamesQuery?

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/repository/metric_names_repository.go
> +	client *pgxpool.Conn
Это все-таки не совсем принято называть клиентом, это именно соединение с БД

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/repository/metric_names_repository.go
> +	if err != nil {
А если эта ошибка таймаут или БД недоступна?
К тому же два запроса у нас выполняются не в одной транзакции, а значит в целом может быть ошибка при одновременной записи двух метрик с одним названием.

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/repository/metrics_repository.go
> +		delta TEXT,
А почему мы храним дельту как текст?

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/repository/metrics_repository.go
> +		if _, err := r.client.Exec(ctx, insertMetricQuery, args); err != nil {
Аналогично 2 запроса не в транзакции выполняются(а если не хранить дельту как текст, то можно сделать одним)

2024-04-16 06:00 UTC, valentinsoe commented on internal/server/repository/metrics_repository.go
> +		err := r.Insert(ctx, metricNames[mt.ID], mt)
И тут нет транзации. Состояние БД после выполнения HTTP-запроса будет слабо детерминированным

2024-04-16 06:00 UTC, valentinsoe commented on cmd/server/handlers/handlers.go
> +		if config.Options.DatabaseDsn == "" {
1) Код хендлера не должен зависеть от используемой реализации хранилища. Нужно использовать интерфейс, которые реализуется всеми 3 типами хранилища.
2) На предыдущих спринтах был "недосмотр":) Хендлер должен возвращать не имена метрик как строки, а HTML страницу с содержимым всех метрик.

2024-05-14 23:02 UTC, avhitrov requested changes
Не очень понимаю, как проверялись предыдущие итерации, поскольку основные ошибки, которые обычно совершают студенты на первых этапах, остались незамеченными. Предлагаю сначала исправить их, а потом уже быстренько разобраться с текущей архитектурой, благо она уже довольно прилично причесана. Итак:
1. Счетчик (PollCount) считает не то, что требует задание. В соответствии с ТЗ он должен подсчитывать количество проходов по сбору метрик, а не отправки. Соответственно, при каждом вызове GarbageStats он должен инкрементироваться, а после успешной (sic!) отправки сбрасываться в 0. Сейчас он подсчитывает количество отправок.
2. В сервере (модель хранения in-memory и файловое хранилище) при конкурентных вызовах на сохранение и чтение вылезают гонки (DATA RACE). Подробности в комментариях к коду.

Если необходимы пояснения по гонкам, предлагаю взять 1-1.

2024-05-15 10:16 UTC, aykuli commented on internal/server/storage/ram/ram.go
> +		CounterMetrics: map[string]int64{},
Добрый день! тема мбтексов идет спринтом 4, и я его сделала в МР для 4го спринта https://github.com/aykuli/observer/pull/17/files#diff-c6abef9e55e0cdbe56626817c7399d9fca4d0613112a8c993a00fe29f0dd86edR19

2024-05-17 07:47 UTC, aykuli commented on internal/server/storage/file/file.go
> +	storeInterval int
добавила мьютекс О-)

2024-05-18 23:12 UTC, avhitrov requested changes
Некоторое количество мелких и не очень мелких замечания в комментариях к коду. Мне не очень понятен смысл продюсера, но я еще посмотрю на код чуть позже, при следующей проверке.

2024-05-18 23:12 UTC, avhitrov commented on internal/server/repository/metrics_repository.go
> +	result := r.conn.QueryRow(ctx, checkMetricExistanceQuery, pgx.NamedArgs{"name": metric.ID, "type": metric.MType})
Огорчу немного. При выполнении данного select блокировки записи не произойдет. Подробности:
https://t.me/bushigo/35
https://t.me/bushigo/36

И еще огорчу. Если сюда не пробросить объект открытой транзакции, то вообще все операции будут выполняться за ее рамками, так что в открытии и закрытии транзакции не будет никакого смысла. Подробности:

https://go.dev/doc/database/execute-transactions

2024-05-18 23:12 UTC, avhitrov commented on internal/server/storage/postgres/postgres.go
> +	metricsRepo := repository.NewMetricsRepository(conn)
По хорошему, открытие и закрытие транзакции следует переместить сюда, раз уж мы используем фабрику, которой скармливаем соединение. В нетранзакционных случаях мы отдаем соединение, а когда нам нужна транзакция - отрываем ее и отдаем tx вместо соединения.

2024-05-19 06:38 UTC, aykuli commented on cmd/agent/client/client.go
>  		m.sendOneMetric(req, mt)
хм... если какая-то из метрик не отправится, но есть предыдущие успешно отправленные, которые сохранились на сервере, в любом случае на сервере будет не консистентная информация. Тогда я лучше сделаю так - выйду из цикла, чтоб хотя бы следующий бач метрик был консистетным.

2024-05-19 07:43 UTC, aykuli commented on cmd/agent/main.go
> +			newClient.SendBatchMetrics(request)
вызов SendMetrics убрала, сам метод не удаляла, а пометила деприкейтед

2024-05-19 07:44 UTC, aykuli commented on cmd/server/handlers/handlers.go
> +		defer r.Body.Close()
действительно)

2024-05-19 07:44 UTC, aykuli commented on cmd/server/handlers/handlers.go
>  		}
спасибо за замечание, да, провела чистку.

2024-05-19 16:07 UTC, aykuli commented on internal/server/repository/metrics_repository.go
> +	}
ясно, спасибо!

2024-05-20 07:20 UTC, aykuli commented on internal/server/storage/postgres/postgres.go
> +	metricsRepo := repository.NewMetricsRepository(conn)
поняла

2024-05-20 07:26 UTC, aykuli commented on internal/server/repository/metrics_repository.go
> +	result := r.conn.QueryRow(ctx, checkMetricExistanceQuery, pgx.NamedArgs{"name": metric.ID, "type": metric.MType})
поняла

2024-05-21 21:20 UTC, avhitrov approved these changes
Замечания исправлены, все должно работать. Можно обсудить (в рамках чата или 1-1) оптимизацию работы с БД.

2024-05-21 21:20 UTC, avhitrov commented on internal/server/storage/postgres/postgres.go
> +	metricsRepo := repository.NewMetricsRepository(conn)
Почти поняла. В принципе, так тоже будет работать, но, насколько я помню, можно tx совать в NewMetricsRepository в качестве conn (хотя надо проверять, насколько у них с conn совместимы интерфейсы) и анализировать ошибку, возвращаемую SelectAllValues. Если nil, то commit, если нет - rollback. Но не буду настаивать на дальнейшей полировке кода.

2024-05-22 08:02 UTC, merged